version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:17.8
    steps:
      - checkout
      - run: echo "this is the new build job"
  test:
    docker:
      - image: cimg/node:17.8
    steps:
      - checkout
      - run: echo "this is the new test job"

workflows:
  build_and_test:
    jobs:
      - build
      - test
