version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:20.5.1
    steps:
      - checkout
      - run: yarn
  test:
    docker:
      - image: cimg/node:20.5.1
    steps:
      - checkout
      - run: yarn test

workflows:
  build_and_test:
    jobs:
      - build
      - test
