version: 2.1

jobs:
  build:
    working_directory: ~/test-app
    docker:
      - image: cimg/node:20.5.1
    steps:
      - checkout
      - attach_workspace:
          at: ~/test-app
      - restore_cache:
          name: Restore Yarn Package Cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          name: Save Yarn Package Cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: .
          paths: .
  test:
    working_directory: ~/test-app
    docker:
      - image: cimg/node:20.5.1
    steps:
      - checkout
      - attach_workspace:
          at: ~/test-app
      - run: yarn test

  deploy:
    working_directory: ~/test-app
    docker:
      - image: cimg/node:20.5.1
    steps:
      - checkout
      - attach_workspace:
          at: ~/test-app
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "cd ~/test-app && git pull && pm2 restart all"

workflows:
  build_and_test_and deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test